#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 29

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COMMA = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_GT = 14,
  anon_sym_DOT = 15,
  sym_ident = 16,
  anon_sym_s = 17,
  anon_sym_e = 18,
  anon_sym_t = 19,
  aux_sym_string_token1 = 20,
  anon_sym_BSLASH_BSLASH = 21,
  anon_sym_BSLASH_DQUOTE = 22,
  aux_sym_string_token2 = 23,
  sym_number = 24,
  aux_sym_symbols_token1 = 25,
  anon_sym_BSLASH_SQUOTE = 26,
  aux_sym_symbols_token2 = 27,
  sym_entry_modifier = 28,
  sym_external_modifier = 29,
  sym_comment = 30,
  sym_line_comment = 31,
  sym_source_file = 32,
  sym_external_declaration = 33,
  sym_function_name_list = 34,
  sym_function_definition = 35,
  sym_body = 36,
  sym_sentence = 37,
  sym_sentence_eq = 38,
  sym_sentence_block = 39,
  sym_sentence_lhs = 40,
  sym_sentence_rhs = 41,
  sym_sentence_block_end = 42,
  aux_sym__pattern = 43,
  sym_grouped_pattern = 44,
  sym_condition = 45,
  aux_sym__expr = 46,
  sym_function_call = 47,
  sym_grouped_expr = 48,
  sym_variable = 49,
  sym__index = 50,
  sym_type = 51,
  sym_string = 52,
  sym_symbols = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_function_name_list_repeat1 = 55,
  aux_sym_body_repeat1 = 56,
  aux_sym_sentence_eq_repeat1 = 57,
  aux_sym_string_repeat1 = 58,
  aux_sym_string_repeat2 = 59,
  aux_sym_symbols_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [aux_sym_string_token2] = "string_token2",
  [sym_number] = "number",
  [aux_sym_symbols_token1] = "symbols_token1",
  [anon_sym_BSLASH_SQUOTE] = "\\'",
  [aux_sym_symbols_token2] = "symbols_token2",
  [sym_entry_modifier] = "entry_modifier",
  [sym_external_modifier] = "external_modifier",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentence_eq] = "sentence_eq",
  [sym_sentence_block] = "sentence_block",
  [sym_sentence_lhs] = "sentence_lhs",
  [sym_sentence_rhs] = "sentence_rhs",
  [sym_sentence_block_end] = "sentence_block_end",
  [aux_sym__pattern] = "_pattern",
  [sym_grouped_pattern] = "grouped_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_function_call] = "function_call",
  [sym_grouped_expr] = "grouped_expr",
  [sym_variable] = "variable",
  [sym__index] = "_index",
  [sym_type] = "type",
  [sym_string] = "string",
  [sym_symbols] = "symbols",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentence_eq_repeat1] = "sentence_eq_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_symbols_repeat1] = "symbols_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_number] = sym_number,
  [aux_sym_symbols_token1] = aux_sym_symbols_token1,
  [anon_sym_BSLASH_SQUOTE] = anon_sym_BSLASH_SQUOTE,
  [aux_sym_symbols_token2] = aux_sym_symbols_token2,
  [sym_entry_modifier] = sym_entry_modifier,
  [sym_external_modifier] = sym_external_modifier,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentence_eq] = sym_sentence_eq,
  [sym_sentence_block] = sym_sentence_block,
  [sym_sentence_lhs] = sym_sentence_lhs,
  [sym_sentence_rhs] = sym_sentence_rhs,
  [sym_sentence_block_end] = sym_sentence_block_end,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_grouped_pattern] = sym_grouped_pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_function_call] = sym_function_call,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_variable] = sym_variable,
  [sym__index] = sym__index,
  [sym_type] = sym_type,
  [sym_string] = sym_string,
  [sym_symbols] = sym_symbols,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentence_eq_repeat1] = aux_sym_sentence_eq_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_symbols_repeat1] = aux_sym_symbols_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symbols_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_symbols_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_lhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_grouped_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym__index] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_eq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbols_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_condition = 3,
  field_entry = 4,
  field_expr = 5,
  field_func_name_list = 6,
  field_lhs = 7,
  field_name = 8,
  field_param = 9,
  field_pattern = 10,
  field_result = 11,
  field_rhs = 12,
  field_sentence_block = 13,
  field_sentence_eq = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_param] = "param",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_sentence_block] = "sentence_block",
  [field_sentence_eq] = "sentence_eq",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 2},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 2},
  [18] = {.index = 23, .length = 2},
  [19] = {.index = 25, .length = 2},
  [20] = {.index = 27, .length = 2},
  [21] = {.index = 29, .length = 2},
  [22] = {.index = 31, .length = 2},
  [23] = {.index = 33, .length = 1},
  [24] = {.index = 34, .length = 2},
  [25] = {.index = 36, .length = 2},
  [26] = {.index = 38, .length = 3},
  [27] = {.index = 41, .length = 3},
  [28] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_sentence_eq, 0},
  [4] =
    {field_sentence_block, 0},
  [5] =
    {field_condition, 0},
  [6] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [9] =
    {field_name, 0},
    {field_name, 1},
  [11] =
    {field_func_name_list, 1},
  [12] =
    {field_block, 1},
  [13] =
    {field_rhs, 1},
  [14] =
    {field_lhs, 0},
  [15] =
    {field_condition, 0, .inherited = true},
  [16] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [18] =
    {field_body, 1},
  [19] =
    {field_pattern, 2},
  [20] =
    {field_result, 1},
  [21] =
    {field_block, 2},
    {field_lhs, 0},
  [23] =
    {field_lhs, 0},
    {field_rhs, 2},
  [25] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [27] =
    {field_name, 2},
    {field_type, 0},
  [29] =
    {field_block, 2},
    {field_condition, 0, .inherited = true},
  [31] =
    {field_condition, 0, .inherited = true},
    {field_rhs, 2},
  [33] =
    {field_name, 1},
  [34] =
    {field_body, 2},
    {field_expr, 0},
  [36] =
    {field_pattern, 3},
    {field_result, 1},
  [38] =
    {field_block, 3},
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [41] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
    {field_rhs, 3},
  [44] =
    {field_name, 1},
    {field_param, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 56,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 41,
        '$', 9,
        '\'', 48,
        '(', 28,
        ')', 29,
        '*', 33,
        '+', 31,
        ',', 23,
        '-', 32,
        '.', 36,
        '/', 34,
        ':', 27,
        ';', 22,
        '<', 30,
        '=', 26,
        '>', 35,
        '\\', 4,
        'e', 39,
        's', 38,
        't', 40,
        '{', 24,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '\'') ADVANCE(48);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(41);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 41,
        '\'', 48,
        '(', 28,
        ')', 29,
        ',', 23,
        '/', 6,
        ':', 27,
        ';', 22,
        '<', 30,
        '=', 26,
        '>', 35,
        'e', 39,
        's', 38,
        't', 40,
        '{', 24,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '/') ADVANCE(34);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(56);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(16);
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'L') ADVANCE(54);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(17);
      if (lookahead == 'X') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(54);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(55);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'Y') ADVANCE(53);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '$', 9,
        ',', 23,
        '.', 36,
        '/', 6,
        ';', 22,
        '=', 26,
        '{', 24,
        '}', 25,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '"') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(42);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(45);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(44);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_symbols_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BSLASH_SQUOTE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '\'') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(42);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(51);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'') ADVANCE(50);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_external_modifier);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_external_modifier);
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 20, .external_lex_state = 1},
  [2] = {.lex_state = 3, .external_lex_state = 1},
  [3] = {.lex_state = 3, .external_lex_state = 1},
  [4] = {.lex_state = 3, .external_lex_state = 1},
  [5] = {.lex_state = 3, .external_lex_state = 1},
  [6] = {.lex_state = 3, .external_lex_state = 1},
  [7] = {.lex_state = 3, .external_lex_state = 1},
  [8] = {.lex_state = 3, .external_lex_state = 1},
  [9] = {.lex_state = 3, .external_lex_state = 1},
  [10] = {.lex_state = 3, .external_lex_state = 1},
  [11] = {.lex_state = 3, .external_lex_state = 1},
  [12] = {.lex_state = 3, .external_lex_state = 1},
  [13] = {.lex_state = 3, .external_lex_state = 1},
  [14] = {.lex_state = 3, .external_lex_state = 1},
  [15] = {.lex_state = 3, .external_lex_state = 1},
  [16] = {.lex_state = 3, .external_lex_state = 1},
  [17] = {.lex_state = 3, .external_lex_state = 1},
  [18] = {.lex_state = 3, .external_lex_state = 1},
  [19] = {.lex_state = 3, .external_lex_state = 1},
  [20] = {.lex_state = 3, .external_lex_state = 1},
  [21] = {.lex_state = 3, .external_lex_state = 1},
  [22] = {.lex_state = 3, .external_lex_state = 1},
  [23] = {.lex_state = 3, .external_lex_state = 1},
  [24] = {.lex_state = 3, .external_lex_state = 1},
  [25] = {.lex_state = 3, .external_lex_state = 1},
  [26] = {.lex_state = 3, .external_lex_state = 1},
  [27] = {.lex_state = 3, .external_lex_state = 1},
  [28] = {.lex_state = 3, .external_lex_state = 1},
  [29] = {.lex_state = 3, .external_lex_state = 1},
  [30] = {.lex_state = 3, .external_lex_state = 1},
  [31] = {.lex_state = 3, .external_lex_state = 1},
  [32] = {.lex_state = 3, .external_lex_state = 1},
  [33] = {.lex_state = 3, .external_lex_state = 1},
  [34] = {.lex_state = 3, .external_lex_state = 1},
  [35] = {.lex_state = 3, .external_lex_state = 1},
  [36] = {.lex_state = 3, .external_lex_state = 1},
  [37] = {.lex_state = 3, .external_lex_state = 1},
  [38] = {.lex_state = 3, .external_lex_state = 1},
  [39] = {.lex_state = 3, .external_lex_state = 1},
  [40] = {.lex_state = 3, .external_lex_state = 1},
  [41] = {.lex_state = 3, .external_lex_state = 1},
  [42] = {.lex_state = 3, .external_lex_state = 1},
  [43] = {.lex_state = 3, .external_lex_state = 1},
  [44] = {.lex_state = 20, .external_lex_state = 1},
  [45] = {.lex_state = 20, .external_lex_state = 1},
  [46] = {.lex_state = 1, .external_lex_state = 1},
  [47] = {.lex_state = 2, .external_lex_state = 1},
  [48] = {.lex_state = 2, .external_lex_state = 1},
  [49] = {.lex_state = 1, .external_lex_state = 1},
  [50] = {.lex_state = 20, .external_lex_state = 1},
  [51] = {.lex_state = 20, .external_lex_state = 1},
  [52] = {.lex_state = 2, .external_lex_state = 1},
  [53] = {.lex_state = 20, .external_lex_state = 1},
  [54] = {.lex_state = 1, .external_lex_state = 1},
  [55] = {.lex_state = 20, .external_lex_state = 1},
  [56] = {.lex_state = 2, .external_lex_state = 1},
  [57] = {.lex_state = 5, .external_lex_state = 1},
  [58] = {.lex_state = 1, .external_lex_state = 1},
  [59] = {.lex_state = 20, .external_lex_state = 1},
  [60] = {.lex_state = 20, .external_lex_state = 1},
  [61] = {.lex_state = 20, .external_lex_state = 1},
  [62] = {.lex_state = 20, .external_lex_state = 1},
  [63] = {.lex_state = 20, .external_lex_state = 1},
  [64] = {.lex_state = 20, .external_lex_state = 1},
  [65] = {.lex_state = 20, .external_lex_state = 1},
  [66] = {.lex_state = 20, .external_lex_state = 1},
  [67] = {.lex_state = 20, .external_lex_state = 1},
  [68] = {.lex_state = 20, .external_lex_state = 1},
  [69] = {.lex_state = 20, .external_lex_state = 1},
  [70] = {.lex_state = 20, .external_lex_state = 1},
  [71] = {.lex_state = 20, .external_lex_state = 1},
  [72] = {.lex_state = 20, .external_lex_state = 1},
  [73] = {.lex_state = 20, .external_lex_state = 1},
  [74] = {.lex_state = 20, .external_lex_state = 1},
  [75] = {.lex_state = 20, .external_lex_state = 1},
  [76] = {.lex_state = 20, .external_lex_state = 1},
  [77] = {.lex_state = 20, .external_lex_state = 1},
  [78] = {.lex_state = 20, .external_lex_state = 1},
  [79] = {.lex_state = 20, .external_lex_state = 1},
  [80] = {.lex_state = 20, .external_lex_state = 1},
  [81] = {.lex_state = 20, .external_lex_state = 1},
  [82] = {.lex_state = 20, .external_lex_state = 1},
  [83] = {.lex_state = 20, .external_lex_state = 1},
  [84] = {.lex_state = 20, .external_lex_state = 1},
  [85] = {.lex_state = 20, .external_lex_state = 1},
  [86] = {.lex_state = 20, .external_lex_state = 1},
  [87] = {.lex_state = 20, .external_lex_state = 1},
  [88] = {.lex_state = 20, .external_lex_state = 1},
  [89] = {.lex_state = 20, .external_lex_state = 1},
  [90] = {.lex_state = 20, .external_lex_state = 1},
  [91] = {.lex_state = 20, .external_lex_state = 1},
  [92] = {.lex_state = 20, .external_lex_state = 1},
  [93] = {.lex_state = 20, .external_lex_state = 1},
  [94] = {.lex_state = 20, .external_lex_state = 1},
  [95] = {.lex_state = 20, .external_lex_state = 1},
  [96] = {.lex_state = 20, .external_lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_symbols_token1] = ACTIONS(1),
    [anon_sym_BSLASH_SQUOTE] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [sym_external_modifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(91),
    [sym_external_declaration] = STATE(45),
    [sym_function_definition] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(45),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_ident] = ACTIONS(9),
    [sym_entry_modifier] = ACTIONS(11),
    [sym_external_modifier] = ACTIONS(13),
    [sym_comment] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 19,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ident,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(62), 1,
      sym_sentence_lhs,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(73), 1,
      sym_sentence_block,
    STATE(78), 1,
      sym_sentence,
    STATE(81), 1,
      sym_sentence_eq,
    STATE(89), 1,
      sym_condition,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(26), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [65] = 19,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ident,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      sym_number,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(62), 1,
      sym_sentence_lhs,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(73), 1,
      sym_sentence_block,
    STATE(81), 1,
      sym_sentence_eq,
    STATE(88), 1,
      sym_sentence,
    STATE(89), 1,
      sym_condition,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(26), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [130] = 19,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    ACTIONS(38), 1,
      anon_sym_RBRACE,
    ACTIONS(40), 1,
      anon_sym_EQ,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      sym_ident,
    ACTIONS(52), 1,
      aux_sym_string_token1,
    ACTIONS(55), 1,
      sym_number,
    ACTIONS(58), 1,
      aux_sym_symbols_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(62), 1,
      sym_sentence_lhs,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(73), 1,
      sym_sentence_block,
    STATE(81), 1,
      sym_sentence_eq,
    STATE(89), 1,
      sym_condition,
    STATE(93), 1,
      sym_type,
    STATE(95), 1,
      sym_sentence,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(49), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(26), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [195] = 11,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      sym_ident,
    ACTIONS(75), 1,
      aux_sym_string_token1,
    ACTIONS(78), 1,
      sym_number,
    ACTIONS(81), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(72), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(61), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [241] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(90), 1,
      sym_ident,
    ACTIONS(92), 1,
      sym_number,
    STATE(82), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [287] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(90), 1,
      sym_ident,
    ACTIONS(92), 1,
      sym_number,
    STATE(77), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [333] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(90), 1,
      sym_ident,
    ACTIONS(92), 1,
      sym_number,
    STATE(74), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(96), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [379] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(90), 1,
      sym_ident,
    ACTIONS(92), 1,
      sym_number,
    STATE(85), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(98), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [425] = 12,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(106), 1,
      sym_number,
    STATE(79), 1,
      sym_body,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [470] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_COLON,
    ACTIONS(110), 1,
      sym_ident,
    ACTIONS(112), 1,
      sym_number,
    STATE(80), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(21), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [515] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      sym_ident,
    ACTIONS(118), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [558] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_COLON,
    ACTIONS(110), 1,
      sym_ident,
    ACTIONS(112), 1,
      sym_number,
    STATE(72), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(21), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [603] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_COLON,
    ACTIONS(110), 1,
      sym_ident,
    ACTIONS(112), 1,
      sym_number,
    STATE(76), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(21), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [648] = 12,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      sym_ident,
    ACTIONS(124), 1,
      sym_number,
    STATE(71), 1,
      sym_body,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(31), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [693] = 12,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      anon_sym_COLON,
    ACTIONS(110), 1,
      sym_ident,
    ACTIONS(112), 1,
      sym_number,
    STATE(84), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(21), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [738] = 10,
    ACTIONS(128), 1,
      anon_sym_LPAREN,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(137), 1,
      aux_sym_string_token1,
    ACTIONS(140), 1,
      sym_number,
    ACTIONS(143), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(126), 3,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
    ACTIONS(134), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [778] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(146), 1,
      anon_sym_GT,
    ACTIONS(148), 1,
      sym_ident,
    ACTIONS(150), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(23), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [820] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(154), 1,
      sym_ident,
    ACTIONS(156), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(20), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [862] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      sym_ident,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [904] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      sym_ident,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(160), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [946] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      sym_ident,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(162), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [988] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(116), 1,
      sym_ident,
    ACTIONS(118), 1,
      sym_number,
    ACTIONS(164), 1,
      anon_sym_GT,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [1030] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_LT,
    ACTIONS(166), 1,
      anon_sym_COLON,
    ACTIONS(168), 1,
      sym_ident,
    ACTIONS(170), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(22), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [1072] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(174), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(172), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1097] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(178), 1,
      sym_ident,
    ACTIONS(180), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1136] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(178), 1,
      sym_ident,
    ACTIONS(180), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1175] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(186), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(184), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1200] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(122), 1,
      sym_ident,
    ACTIONS(124), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(120), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(31), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1239] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(190), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(188), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1264] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(178), 1,
      sym_ident,
    ACTIONS(180), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(192), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1303] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(196), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(194), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1328] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(200), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(198), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1353] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(104), 1,
      sym_ident,
    ACTIONS(106), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1392] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(178), 1,
      sym_ident,
    ACTIONS(180), 1,
      sym_number,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1430] = 10,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(31), 1,
      aux_sym_symbols_token1,
    ACTIONS(204), 1,
      anon_sym_RPAREN,
    ACTIONS(206), 1,
      sym_ident,
    ACTIONS(208), 1,
      sym_number,
    STATE(93), 1,
      sym_type,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(35), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1468] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(212), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(210), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1491] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(216), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(214), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1514] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(220), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(218), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1537] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(224), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(222), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1560] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(226), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(38), 7,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1580] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(230), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(228), 7,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1600] = 3,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(234), 4,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(232), 7,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
      sym_number,
      aux_sym_symbols_token1,
  [1620] = 6,
    ACTIONS(236), 1,
      ts_builtin_sym_end,
    ACTIONS(238), 1,
      sym_ident,
    ACTIONS(241), 1,
      sym_entry_modifier,
    ACTIONS(244), 1,
      sym_external_modifier,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    STATE(44), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1642] = 6,
    ACTIONS(9), 1,
      sym_ident,
    ACTIONS(11), 1,
      sym_entry_modifier,
    ACTIONS(13), 1,
      sym_external_modifier,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    STATE(44), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1664] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(251), 1,
      aux_sym_symbols_token1,
    STATE(49), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(249), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1683] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(253), 1,
      aux_sym_string_token1,
    STATE(47), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(255), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1702] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(258), 1,
      aux_sym_string_token1,
    STATE(47), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(260), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1721] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(265), 1,
      aux_sym_symbols_token1,
    STATE(49), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(262), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1740] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(267), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1753] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(269), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1766] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(271), 1,
      aux_sym_string_token1,
    STATE(48), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(273), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1785] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(275), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1798] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(279), 1,
      aux_sym_symbols_token1,
    STATE(46), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(277), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1817] = 3,
    ACTIONS(283), 1,
      anon_sym_SEMI,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(281), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1831] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(287), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(56), 1,
      aux_sym_string_repeat1,
    ACTIONS(285), 3,
      aux_sym_string_token1,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1849] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(290), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_ident,
  [1863] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(5), 1,
      sym_line_comment,
    ACTIONS(292), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(58), 1,
      aux_sym_string_repeat1,
    ACTIONS(285), 3,
      aux_sym_symbols_token1,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1881] = 3,
    ACTIONS(297), 1,
      anon_sym_SEMI,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(295), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1895] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(299), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1906] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(301), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1917] = 5,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [1934] = 5,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_EQ,
    STATE(65), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [1951] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(311), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1962] = 5,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    ACTIONS(316), 1,
      anon_sym_EQ,
    STATE(65), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [1979] = 5,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_EQ,
    STATE(65), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [1996] = 4,
    ACTIONS(322), 1,
      anon_sym_SEMI,
    ACTIONS(324), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2010] = 4,
    ACTIONS(324), 1,
      anon_sym_COMMA,
    ACTIONS(326), 1,
      anon_sym_SEMI,
    STATE(67), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2024] = 3,
    STATE(33), 1,
      sym__index,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(328), 2,
      sym_ident,
      sym_number,
  [2036] = 4,
    ACTIONS(330), 1,
      anon_sym_SEMI,
    ACTIONS(332), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2050] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(335), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2059] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(337), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2068] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(339), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2077] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(341), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2086] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(330), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [2095] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(343), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2104] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(345), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2113] = 3,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(347), 1,
      anon_sym_SEMI,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2124] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(349), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2133] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(351), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2142] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(353), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2151] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(355), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2160] = 3,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_body,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2171] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(357), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2180] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(359), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2189] = 3,
    ACTIONS(102), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_body,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2200] = 3,
    ACTIONS(361), 1,
      sym_ident,
    STATE(94), 1,
      sym_function_name_list,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2211] = 3,
    ACTIONS(347), 1,
      anon_sym_SEMI,
    ACTIONS(363), 1,
      anon_sym_RBRACE,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2222] = 2,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
    ACTIONS(365), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
  [2231] = 2,
    ACTIONS(367), 1,
      sym_ident,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2239] = 2,
    ACTIONS(369), 1,
      ts_builtin_sym_end,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2247] = 2,
    ACTIONS(371), 1,
      anon_sym_DOT,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2255] = 2,
    ACTIONS(373), 1,
      anon_sym_DOT,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2263] = 2,
    ACTIONS(375), 1,
      anon_sym_SEMI,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2271] = 2,
    ACTIONS(347), 1,
      anon_sym_SEMI,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
  [2279] = 2,
    ACTIONS(377), 1,
      sym_ident,
    ACTIONS(5), 2,
      sym_line_comment,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 65,
  [SMALL_STATE(4)] = 130,
  [SMALL_STATE(5)] = 195,
  [SMALL_STATE(6)] = 241,
  [SMALL_STATE(7)] = 287,
  [SMALL_STATE(8)] = 333,
  [SMALL_STATE(9)] = 379,
  [SMALL_STATE(10)] = 425,
  [SMALL_STATE(11)] = 470,
  [SMALL_STATE(12)] = 515,
  [SMALL_STATE(13)] = 558,
  [SMALL_STATE(14)] = 603,
  [SMALL_STATE(15)] = 648,
  [SMALL_STATE(16)] = 693,
  [SMALL_STATE(17)] = 738,
  [SMALL_STATE(18)] = 778,
  [SMALL_STATE(19)] = 820,
  [SMALL_STATE(20)] = 862,
  [SMALL_STATE(21)] = 904,
  [SMALL_STATE(22)] = 946,
  [SMALL_STATE(23)] = 988,
  [SMALL_STATE(24)] = 1030,
  [SMALL_STATE(25)] = 1072,
  [SMALL_STATE(26)] = 1097,
  [SMALL_STATE(27)] = 1136,
  [SMALL_STATE(28)] = 1175,
  [SMALL_STATE(29)] = 1200,
  [SMALL_STATE(30)] = 1239,
  [SMALL_STATE(31)] = 1264,
  [SMALL_STATE(32)] = 1303,
  [SMALL_STATE(33)] = 1328,
  [SMALL_STATE(34)] = 1353,
  [SMALL_STATE(35)] = 1392,
  [SMALL_STATE(36)] = 1430,
  [SMALL_STATE(37)] = 1468,
  [SMALL_STATE(38)] = 1491,
  [SMALL_STATE(39)] = 1514,
  [SMALL_STATE(40)] = 1537,
  [SMALL_STATE(41)] = 1560,
  [SMALL_STATE(42)] = 1580,
  [SMALL_STATE(43)] = 1600,
  [SMALL_STATE(44)] = 1620,
  [SMALL_STATE(45)] = 1642,
  [SMALL_STATE(46)] = 1664,
  [SMALL_STATE(47)] = 1683,
  [SMALL_STATE(48)] = 1702,
  [SMALL_STATE(49)] = 1721,
  [SMALL_STATE(50)] = 1740,
  [SMALL_STATE(51)] = 1753,
  [SMALL_STATE(52)] = 1766,
  [SMALL_STATE(53)] = 1785,
  [SMALL_STATE(54)] = 1798,
  [SMALL_STATE(55)] = 1817,
  [SMALL_STATE(56)] = 1831,
  [SMALL_STATE(57)] = 1849,
  [SMALL_STATE(58)] = 1863,
  [SMALL_STATE(59)] = 1881,
  [SMALL_STATE(60)] = 1895,
  [SMALL_STATE(61)] = 1906,
  [SMALL_STATE(62)] = 1917,
  [SMALL_STATE(63)] = 1934,
  [SMALL_STATE(64)] = 1951,
  [SMALL_STATE(65)] = 1962,
  [SMALL_STATE(66)] = 1979,
  [SMALL_STATE(67)] = 1996,
  [SMALL_STATE(68)] = 2010,
  [SMALL_STATE(69)] = 2024,
  [SMALL_STATE(70)] = 2036,
  [SMALL_STATE(71)] = 2050,
  [SMALL_STATE(72)] = 2059,
  [SMALL_STATE(73)] = 2068,
  [SMALL_STATE(74)] = 2077,
  [SMALL_STATE(75)] = 2086,
  [SMALL_STATE(76)] = 2095,
  [SMALL_STATE(77)] = 2104,
  [SMALL_STATE(78)] = 2113,
  [SMALL_STATE(79)] = 2124,
  [SMALL_STATE(80)] = 2133,
  [SMALL_STATE(81)] = 2142,
  [SMALL_STATE(82)] = 2151,
  [SMALL_STATE(83)] = 2160,
  [SMALL_STATE(84)] = 2171,
  [SMALL_STATE(85)] = 2180,
  [SMALL_STATE(86)] = 2189,
  [SMALL_STATE(87)] = 2200,
  [SMALL_STATE(88)] = 2211,
  [SMALL_STATE(89)] = 2222,
  [SMALL_STATE(90)] = 2231,
  [SMALL_STATE(91)] = 2239,
  [SMALL_STATE(92)] = 2247,
  [SMALL_STATE(93)] = 2255,
  [SMALL_STATE(94)] = 2263,
  [SMALL_STATE(95)] = 2271,
  [SMALL_STATE(96)] = 2279,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(19),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(57),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(92),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(52),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(54),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 12),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 11),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 19),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_rhs, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 16),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(36),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(17),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(92),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(52),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(17),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(54),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_lhs, 1, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 15),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 2, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 25),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 20),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 20),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 23),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 23),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 28),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 28),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [241] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [255] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(47),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [262] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 6),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [292] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 1),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 6),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13), SHIFT_REPEAT(24),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 2, 0, 7),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 2),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0),
  [332] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 3, 0, 24),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 17),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 4),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 18),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 21),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 22),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 2, 0, 14),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 2, 0, 9),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 3),
  [355] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 10),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 4, 0, 26),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 4, 0, 27),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 1, 0, 5),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [369] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [371] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_line_comment = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_line_comment] = sym_line_comment,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_line_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_refal5_external_scanner_create(void);
void tree_sitter_refal5_external_scanner_destroy(void *);
bool tree_sitter_refal5_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_refal5_external_scanner_serialize(void *, char *);
void tree_sitter_refal5_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_refal5_external_scanner_create,
      tree_sitter_refal5_external_scanner_destroy,
      tree_sitter_refal5_external_scanner_scan,
      tree_sitter_refal5_external_scanner_serialize,
      tree_sitter_refal5_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
